language: python

#python:
#  - "2.6"
#  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"
#  - "3.5"
#  - "3.5-dev" # 3.5 development branch
#  - "nightly" # currently points to 3.6-dev

# OSX not supported:
#   https://docs.travis-ci.com/user/multi-os/
#   https://docs.travis-ci.com/user/languages/pythonc
#os:
#  - linux
#  - osx

sudo: required

matrix:
    include:
        - python: 3.2
          env: TOXENV=py32
        - python: 3.3
          env: TOXENV=py33
#        - language: generic
#          os: osx
#          osx_image: xcode7.1
#          env: TOXENV=py32
#        - language: generic
#          os: osx
#          osx_image: xcode7.1
#          env: TOXENV=py33

#before_install:
#  - ./.travis/install.sh
#  - pip install coverage
#  - pip install codecov

# command to install dependencies
#install: "pip install -r requirements.txt"
install:
  - ./.travis/install.sh

# command to run tests
script:
  - ./.travis/run.sh

after_success:
  - coverage run -m test_rational.test_rational
  - codecov
