language: python

matrix:
  include:
    - python "3.4"
      env: PYTHON_VERSION=3.4
    - python "3.5"
      env: PYTHON_VERSION=3.5

os:
  - linux
  - osx

install: ./.travis/install.sh

# command to run tests
script: python setup.py test
