language: python

python:
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev

# OSX not supported:
#   https://docs.travis-ci.com/user/multi-os/
#   https://docs.travis-ci.com/user/languages/pythonc
os:
  - linux
#  - osx

# command to run tests
script: python setup.py test
