language: python

cache:
  directories:
    - $HOME/.cache/pip

matrix:
    include:
        # Linux
        - python: 2.6
          env: TOXENV=py26
        - python: 2.7
          env: TOXENV=py27
        - python: 3.3
          env: TOXENV=py33
        - python: 3.4
          env: TOXENV=py34
        - python: 3.5
          env: TOXENV=py35
        # OSX Xcode 7.1
        - language: generic
          os: osx
          osx_image: xcode7.1
          env: TOXENV=py26
        - language: generic
          os: osx
          osx_image: xcode7.1
          env: TOXENV=py27
        - language: generic
          os: osx
          osx_image: xcode7.1
          env: TOXENV=py33
        - language: generic
          os: osx
          osx_image: xcode7.1
          env: TOXENV=py34
        - language: generic
          os: osx
          osx_image: xcode7.1
          env: TOXENV=py35
        # OSX Xcode 7.2
        - language: generic
          os: osx
          osx_image: xcode7.2
          env: TOXENV=py26
        - language: generic
          os: osx
          osx_image: xcode7.2
          env: TOXENV=py27
        - language: generic
          os: osx
          osx_image: xcode7.2
          env: TOXENV=py33
        - language: generic
          os: osx
          osx_image: xcode7.2
          env: TOXENV=py34
        - language: generic
          os: osx
          osx_image: xcode7.2
          env: TOXENV=py35
        # OSX Xcode 7.3
        - language: generic
          os: osx
          osx_image: xcode7.3
          env: TOXENV=py26
        - language: generic
          os: osx
          osx_image: xcode7.3
          env: TOXENV=py27
        - language: generic
          os: osx
          osx_image: xcode7.3
          env: TOXENV=py33
        - language: generic
          os: osx
          osx_image: xcode7.3
          env: TOXENV=py34
        - language: generic
          os: osx
          osx_image: xcode7.3
          env: TOXENV=py35

# command to install dependencies
install:
  - ./.travis/install.sh

# command to run tests
script:
  - ./.travis/run.sh

after_success:
  - coverage run -m test_rational.test_rational
  - codecov
